### PR TITLE
Use lodash's get() to allow for nested field values in constraints

### PR DESCRIPTION
**Pull request by hstonge**
Here's the feature: by using [lodash's get()](https://lodash.com/docs/3.10.1#get) instead of the bracket accessor syntax ( `[]` ), we can easily use a path matching nested properties in the source objects.

So if you have the following source object:
```
{
  "name": "Kamryn Rempel",
  "age": 48,
  "email": "Fabian.Ernser54@gmail.com",
  "meta": {
    "active": true
  }
}
```
then we can have a constraint config object like so:
```
{
  "Name": "name",
  "Age": "age",
  "Email": "email",
  "Active": "meta.active"
}
```

### CODE REVIEW

**Comment by hstonge** [comment]
Also see issue #2

**Comment by nickpisacane** [comment]
Thanks, @hstonge! I'll merge and bump version

**Comment by hstonge** [comment]
Thanks to you @nickpisacane ! Will you update the dependency for this module in your [mongooseToCsv](https://github.com/nickpisacane/mongooseToCsv) ? :)

**Comment by nickpisacane** [comment]
Absolutely! Thanks for the reminder :)

**Pull request merged**
